eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.207:8761/eureka/
      
server:
  port: 8762
  
spring:
  application:
    name: eshop-product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.205:3306/eshop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  rabbitmq:
    host: 192.168.1.205
    port: 5672  
    username: rabbitadmin  
    password: 123456
    virtual-host: /eshop